version: '3.2'

services:
  wall_history_php:
    build:
      context: ./.docker
    container_name: wall_history_php
    extra_hosts:
      - host.docker.internal:host-gateway
    ports:
      - '8001:80'
    volumes:
      - ./:/var/www/html
    user: "ubuntu"
    networks:
      - shared_network
    depends_on:
      - wall_history_mysql

  wall_history_mysql:
    image: mysql:5.6
    container_name: wall_history_mysql
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ".docker/data/db:/var/lib/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-wall_history}
      MYSQL_DATABASE: ${MYSQL_DATABASE:-wall_history}
      MYSQL_USER: ${MYSQL_USER:-wall_history}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-wall_history}
    ports:
      - '3336:3306'
    networks:
      - shared_network
networks:
  shared_network:
    name: my_shared_network
